site:
  title: USFM Docs
  url: https://docs.usfm.bible
  start_page: ROOT::index.adoc
  robots: allow
git:
  ensure_git_suffix: true
content:
  sources:
  - url: https://github.com/klassenjm/docs-src
    branches: main
    start_path: docs/usfm
output:
  dir: ./public
asciidoc:
  attributes:
    example-caption: false
    listing-caption: false
    url-org: https://usfm.bible
    url-project: https://docs.usfm.bible
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true